# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wusel/Development/QT5/ClamAV-GUI

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wusel/Development/QT5/ClamAV-GUI

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/wusel/Development/QT5/ClamAV-GUI/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wusel/Development/QT5/ClamAV-GUI/CMakeFiles /home/wusel/Development/QT5/ClamAV-GUI//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wusel/Development/QT5/ClamAV-GUI/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ClamAV-GUI

# Build rule for target.
ClamAV-GUI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ClamAV-GUI
.PHONY : ClamAV-GUI

# fast build rule for target.
ClamAV-GUI/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/build
.PHONY : ClamAV-GUI/fast

#=============================================================================
# Target rules for targets named ClamAV-GUI_autogen_timestamp_deps

# Build rule for target.
ClamAV-GUI_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ClamAV-GUI_autogen_timestamp_deps
.PHONY : ClamAV-GUI_autogen_timestamp_deps

# fast build rule for target.
ClamAV-GUI_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI_autogen_timestamp_deps.dir/build.make CMakeFiles/ClamAV-GUI_autogen_timestamp_deps.dir/build
.PHONY : ClamAV-GUI_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named ClamAV-GUI_autogen

# Build rule for target.
ClamAV-GUI_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ClamAV-GUI_autogen
.PHONY : ClamAV-GUI_autogen

# fast build rule for target.
ClamAV-GUI_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI_autogen.dir/build.make CMakeFiles/ClamAV-GUI_autogen.dir/build
.PHONY : ClamAV-GUI_autogen/fast

ClamAV-GUI_autogen/EWIEGA46WW/qrc_resources.o: ClamAV-GUI_autogen/EWIEGA46WW/qrc_resources.cpp.o
.PHONY : ClamAV-GUI_autogen/EWIEGA46WW/qrc_resources.o

# target to build an object file
ClamAV-GUI_autogen/EWIEGA46WW/qrc_resources.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/ClamAV-GUI_autogen/EWIEGA46WW/qrc_resources.cpp.o
.PHONY : ClamAV-GUI_autogen/EWIEGA46WW/qrc_resources.cpp.o

ClamAV-GUI_autogen/EWIEGA46WW/qrc_resources.i: ClamAV-GUI_autogen/EWIEGA46WW/qrc_resources.cpp.i
.PHONY : ClamAV-GUI_autogen/EWIEGA46WW/qrc_resources.i

# target to preprocess a source file
ClamAV-GUI_autogen/EWIEGA46WW/qrc_resources.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/ClamAV-GUI_autogen/EWIEGA46WW/qrc_resources.cpp.i
.PHONY : ClamAV-GUI_autogen/EWIEGA46WW/qrc_resources.cpp.i

ClamAV-GUI_autogen/EWIEGA46WW/qrc_resources.s: ClamAV-GUI_autogen/EWIEGA46WW/qrc_resources.cpp.s
.PHONY : ClamAV-GUI_autogen/EWIEGA46WW/qrc_resources.s

# target to generate assembly for a file
ClamAV-GUI_autogen/EWIEGA46WW/qrc_resources.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/ClamAV-GUI_autogen/EWIEGA46WW/qrc_resources.cpp.s
.PHONY : ClamAV-GUI_autogen/EWIEGA46WW/qrc_resources.cpp.s

ClamAV-GUI_autogen/mocs_compilation.o: ClamAV-GUI_autogen/mocs_compilation.cpp.o
.PHONY : ClamAV-GUI_autogen/mocs_compilation.o

# target to build an object file
ClamAV-GUI_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/ClamAV-GUI_autogen/mocs_compilation.cpp.o
.PHONY : ClamAV-GUI_autogen/mocs_compilation.cpp.o

ClamAV-GUI_autogen/mocs_compilation.i: ClamAV-GUI_autogen/mocs_compilation.cpp.i
.PHONY : ClamAV-GUI_autogen/mocs_compilation.i

# target to preprocess a source file
ClamAV-GUI_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/ClamAV-GUI_autogen/mocs_compilation.cpp.i
.PHONY : ClamAV-GUI_autogen/mocs_compilation.cpp.i

ClamAV-GUI_autogen/mocs_compilation.s: ClamAV-GUI_autogen/mocs_compilation.cpp.s
.PHONY : ClamAV-GUI_autogen/mocs_compilation.s

# target to generate assembly for a file
ClamAV-GUI_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/ClamAV-GUI_autogen/mocs_compilation.cpp.s
.PHONY : ClamAV-GUI_autogen/mocs_compilation.cpp.s

src/cfilesystemmodel.o: src/cfilesystemmodel.cpp.o
.PHONY : src/cfilesystemmodel.o

# target to build an object file
src/cfilesystemmodel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/cfilesystemmodel.cpp.o
.PHONY : src/cfilesystemmodel.cpp.o

src/cfilesystemmodel.i: src/cfilesystemmodel.cpp.i
.PHONY : src/cfilesystemmodel.i

# target to preprocess a source file
src/cfilesystemmodel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/cfilesystemmodel.cpp.i
.PHONY : src/cfilesystemmodel.cpp.i

src/cfilesystemmodel.s: src/cfilesystemmodel.cpp.s
.PHONY : src/cfilesystemmodel.s

# target to generate assembly for a file
src/cfilesystemmodel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/cfilesystemmodel.cpp.s
.PHONY : src/cfilesystemmodel.cpp.s

src/clamav_ctrl.o: src/clamav_ctrl.cpp.o
.PHONY : src/clamav_ctrl.o

# target to build an object file
src/clamav_ctrl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/clamav_ctrl.cpp.o
.PHONY : src/clamav_ctrl.cpp.o

src/clamav_ctrl.i: src/clamav_ctrl.cpp.i
.PHONY : src/clamav_ctrl.i

# target to preprocess a source file
src/clamav_ctrl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/clamav_ctrl.cpp.i
.PHONY : src/clamav_ctrl.cpp.i

src/clamav_ctrl.s: src/clamav_ctrl.cpp.s
.PHONY : src/clamav_ctrl.s

# target to generate assembly for a file
src/clamav_ctrl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/clamav_ctrl.cpp.s
.PHONY : src/clamav_ctrl.cpp.s

src/clamav_gui.o: src/clamav_gui.cpp.o
.PHONY : src/clamav_gui.o

# target to build an object file
src/clamav_gui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/clamav_gui.cpp.o
.PHONY : src/clamav_gui.cpp.o

src/clamav_gui.i: src/clamav_gui.cpp.i
.PHONY : src/clamav_gui.i

# target to preprocess a source file
src/clamav_gui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/clamav_gui.cpp.i
.PHONY : src/clamav_gui.cpp.i

src/clamav_gui.s: src/clamav_gui.cpp.s
.PHONY : src/clamav_gui.s

# target to generate assembly for a file
src/clamav_gui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/clamav_gui.cpp.s
.PHONY : src/clamav_gui.cpp.s

src/clamdconfcomboboxoption.o: src/clamdconfcomboboxoption.cpp.o
.PHONY : src/clamdconfcomboboxoption.o

# target to build an object file
src/clamdconfcomboboxoption.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/clamdconfcomboboxoption.cpp.o
.PHONY : src/clamdconfcomboboxoption.cpp.o

src/clamdconfcomboboxoption.i: src/clamdconfcomboboxoption.cpp.i
.PHONY : src/clamdconfcomboboxoption.i

# target to preprocess a source file
src/clamdconfcomboboxoption.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/clamdconfcomboboxoption.cpp.i
.PHONY : src/clamdconfcomboboxoption.cpp.i

src/clamdconfcomboboxoption.s: src/clamdconfcomboboxoption.cpp.s
.PHONY : src/clamdconfcomboboxoption.s

# target to generate assembly for a file
src/clamdconfcomboboxoption.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/clamdconfcomboboxoption.cpp.s
.PHONY : src/clamdconfcomboboxoption.cpp.s

src/clamdconfspinboxoption.o: src/clamdconfspinboxoption.cpp.o
.PHONY : src/clamdconfspinboxoption.o

# target to build an object file
src/clamdconfspinboxoption.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/clamdconfspinboxoption.cpp.o
.PHONY : src/clamdconfspinboxoption.cpp.o

src/clamdconfspinboxoption.i: src/clamdconfspinboxoption.cpp.i
.PHONY : src/clamdconfspinboxoption.i

# target to preprocess a source file
src/clamdconfspinboxoption.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/clamdconfspinboxoption.cpp.i
.PHONY : src/clamdconfspinboxoption.cpp.i

src/clamdconfspinboxoption.s: src/clamdconfspinboxoption.cpp.s
.PHONY : src/clamdconfspinboxoption.s

# target to generate assembly for a file
src/clamdconfspinboxoption.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/clamdconfspinboxoption.cpp.s
.PHONY : src/clamdconfspinboxoption.cpp.s

src/clamdconfstringoption.o: src/clamdconfstringoption.cpp.o
.PHONY : src/clamdconfstringoption.o

# target to build an object file
src/clamdconfstringoption.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/clamdconfstringoption.cpp.o
.PHONY : src/clamdconfstringoption.cpp.o

src/clamdconfstringoption.i: src/clamdconfstringoption.cpp.i
.PHONY : src/clamdconfstringoption.i

# target to preprocess a source file
src/clamdconfstringoption.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/clamdconfstringoption.cpp.i
.PHONY : src/clamdconfstringoption.cpp.i

src/clamdconfstringoption.s: src/clamdconfstringoption.cpp.s
.PHONY : src/clamdconfstringoption.s

# target to generate assembly for a file
src/clamdconfstringoption.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/clamdconfstringoption.cpp.s
.PHONY : src/clamdconfstringoption.cpp.s

src/clamdmanager.o: src/clamdmanager.cpp.o
.PHONY : src/clamdmanager.o

# target to build an object file
src/clamdmanager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/clamdmanager.cpp.o
.PHONY : src/clamdmanager.cpp.o

src/clamdmanager.i: src/clamdmanager.cpp.i
.PHONY : src/clamdmanager.i

# target to preprocess a source file
src/clamdmanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/clamdmanager.cpp.i
.PHONY : src/clamdmanager.cpp.i

src/clamdmanager.s: src/clamdmanager.cpp.s
.PHONY : src/clamdmanager.s

# target to generate assembly for a file
src/clamdmanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/clamdmanager.cpp.s
.PHONY : src/clamdmanager.cpp.s

src/dragablepushbutton.o: src/dragablepushbutton.cpp.o
.PHONY : src/dragablepushbutton.o

# target to build an object file
src/dragablepushbutton.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/dragablepushbutton.cpp.o
.PHONY : src/dragablepushbutton.cpp.o

src/dragablepushbutton.i: src/dragablepushbutton.cpp.i
.PHONY : src/dragablepushbutton.i

# target to preprocess a source file
src/dragablepushbutton.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/dragablepushbutton.cpp.i
.PHONY : src/dragablepushbutton.cpp.i

src/dragablepushbutton.s: src/dragablepushbutton.cpp.s
.PHONY : src/dragablepushbutton.s

# target to generate assembly for a file
src/dragablepushbutton.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/dragablepushbutton.cpp.s
.PHONY : src/dragablepushbutton.cpp.s

src/freshclamsetter.o: src/freshclamsetter.cpp.o
.PHONY : src/freshclamsetter.o

# target to build an object file
src/freshclamsetter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/freshclamsetter.cpp.o
.PHONY : src/freshclamsetter.cpp.o

src/freshclamsetter.i: src/freshclamsetter.cpp.i
.PHONY : src/freshclamsetter.i

# target to preprocess a source file
src/freshclamsetter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/freshclamsetter.cpp.i
.PHONY : src/freshclamsetter.cpp.i

src/freshclamsetter.s: src/freshclamsetter.cpp.s
.PHONY : src/freshclamsetter.s

# target to generate assembly for a file
src/freshclamsetter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/freshclamsetter.cpp.s
.PHONY : src/freshclamsetter.cpp.s

src/highlighter.o: src/highlighter.cpp.o
.PHONY : src/highlighter.o

# target to build an object file
src/highlighter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/highlighter.cpp.o
.PHONY : src/highlighter.cpp.o

src/highlighter.i: src/highlighter.cpp.i
.PHONY : src/highlighter.i

# target to preprocess a source file
src/highlighter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/highlighter.cpp.i
.PHONY : src/highlighter.cpp.i

src/highlighter.s: src/highlighter.cpp.s
.PHONY : src/highlighter.s

# target to generate assembly for a file
src/highlighter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/highlighter.cpp.s
.PHONY : src/highlighter.cpp.s

src/includeexcludeoptions.o: src/includeexcludeoptions.cpp.o
.PHONY : src/includeexcludeoptions.o

# target to build an object file
src/includeexcludeoptions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/includeexcludeoptions.cpp.o
.PHONY : src/includeexcludeoptions.cpp.o

src/includeexcludeoptions.i: src/includeexcludeoptions.cpp.i
.PHONY : src/includeexcludeoptions.i

# target to preprocess a source file
src/includeexcludeoptions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/includeexcludeoptions.cpp.i
.PHONY : src/includeexcludeoptions.cpp.i

src/includeexcludeoptions.s: src/includeexcludeoptions.cpp.s
.PHONY : src/includeexcludeoptions.s

# target to generate assembly for a file
src/includeexcludeoptions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/includeexcludeoptions.cpp.s
.PHONY : src/includeexcludeoptions.cpp.s

src/infodialog.o: src/infodialog.cpp.o
.PHONY : src/infodialog.o

# target to build an object file
src/infodialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/infodialog.cpp.o
.PHONY : src/infodialog.cpp.o

src/infodialog.i: src/infodialog.cpp.i
.PHONY : src/infodialog.i

# target to preprocess a source file
src/infodialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/infodialog.cpp.i
.PHONY : src/infodialog.cpp.i

src/infodialog.s: src/infodialog.cpp.s
.PHONY : src/infodialog.s

# target to generate assembly for a file
src/infodialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/infodialog.cpp.s
.PHONY : src/infodialog.cpp.s

src/logviewerobject.o: src/logviewerobject.cpp.o
.PHONY : src/logviewerobject.o

# target to build an object file
src/logviewerobject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/logviewerobject.cpp.o
.PHONY : src/logviewerobject.cpp.o

src/logviewerobject.i: src/logviewerobject.cpp.i
.PHONY : src/logviewerobject.i

# target to preprocess a source file
src/logviewerobject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/logviewerobject.cpp.i
.PHONY : src/logviewerobject.cpp.i

src/logviewerobject.s: src/logviewerobject.cpp.s
.PHONY : src/logviewerobject.s

# target to generate assembly for a file
src/logviewerobject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/logviewerobject.cpp.s
.PHONY : src/logviewerobject.cpp.s

src/logviewobject.o: src/logviewobject.cpp.o
.PHONY : src/logviewobject.o

# target to build an object file
src/logviewobject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/logviewobject.cpp.o
.PHONY : src/logviewobject.cpp.o

src/logviewobject.i: src/logviewobject.cpp.i
.PHONY : src/logviewobject.i

# target to preprocess a source file
src/logviewobject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/logviewobject.cpp.i
.PHONY : src/logviewobject.cpp.i

src/logviewobject.s: src/logviewobject.cpp.s
.PHONY : src/logviewobject.s

# target to generate assembly for a file
src/logviewobject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/logviewobject.cpp.s
.PHONY : src/logviewobject.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/myframe.o: src/myframe.cpp.o
.PHONY : src/myframe.o

# target to build an object file
src/myframe.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/myframe.cpp.o
.PHONY : src/myframe.cpp.o

src/myframe.i: src/myframe.cpp.i
.PHONY : src/myframe.i

# target to preprocess a source file
src/myframe.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/myframe.cpp.i
.PHONY : src/myframe.cpp.i

src/myframe.s: src/myframe.cpp.s
.PHONY : src/myframe.s

# target to generate assembly for a file
src/myframe.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/myframe.cpp.s
.PHONY : src/myframe.cpp.s

src/optionsdialog.o: src/optionsdialog.cpp.o
.PHONY : src/optionsdialog.o

# target to build an object file
src/optionsdialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/optionsdialog.cpp.o
.PHONY : src/optionsdialog.cpp.o

src/optionsdialog.i: src/optionsdialog.cpp.i
.PHONY : src/optionsdialog.i

# target to preprocess a source file
src/optionsdialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/optionsdialog.cpp.i
.PHONY : src/optionsdialog.cpp.i

src/optionsdialog.s: src/optionsdialog.cpp.s
.PHONY : src/optionsdialog.s

# target to generate assembly for a file
src/optionsdialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/optionsdialog.cpp.s
.PHONY : src/optionsdialog.cpp.s

src/partiallogobject.o: src/partiallogobject.cpp.o
.PHONY : src/partiallogobject.o

# target to build an object file
src/partiallogobject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/partiallogobject.cpp.o
.PHONY : src/partiallogobject.cpp.o

src/partiallogobject.i: src/partiallogobject.cpp.i
.PHONY : src/partiallogobject.i

# target to preprocess a source file
src/partiallogobject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/partiallogobject.cpp.i
.PHONY : src/partiallogobject.cpp.i

src/partiallogobject.s: src/partiallogobject.cpp.s
.PHONY : src/partiallogobject.s

# target to generate assembly for a file
src/partiallogobject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/partiallogobject.cpp.s
.PHONY : src/partiallogobject.cpp.s

src/profilemanager.o: src/profilemanager.cpp.o
.PHONY : src/profilemanager.o

# target to build an object file
src/profilemanager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/profilemanager.cpp.o
.PHONY : src/profilemanager.cpp.o

src/profilemanager.i: src/profilemanager.cpp.i
.PHONY : src/profilemanager.i

# target to preprocess a source file
src/profilemanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/profilemanager.cpp.i
.PHONY : src/profilemanager.cpp.i

src/profilemanager.s: src/profilemanager.cpp.s
.PHONY : src/profilemanager.s

# target to generate assembly for a file
src/profilemanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/profilemanager.cpp.s
.PHONY : src/profilemanager.cpp.s

src/profilewizarddialog.o: src/profilewizarddialog.cpp.o
.PHONY : src/profilewizarddialog.o

# target to build an object file
src/profilewizarddialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/profilewizarddialog.cpp.o
.PHONY : src/profilewizarddialog.cpp.o

src/profilewizarddialog.i: src/profilewizarddialog.cpp.i
.PHONY : src/profilewizarddialog.i

# target to preprocess a source file
src/profilewizarddialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/profilewizarddialog.cpp.i
.PHONY : src/profilewizarddialog.cpp.i

src/profilewizarddialog.s: src/profilewizarddialog.cpp.s
.PHONY : src/profilewizarddialog.s

# target to generate assembly for a file
src/profilewizarddialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/profilewizarddialog.cpp.s
.PHONY : src/profilewizarddialog.cpp.s

src/progressdialog.o: src/progressdialog.cpp.o
.PHONY : src/progressdialog.o

# target to build an object file
src/progressdialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/progressdialog.cpp.o
.PHONY : src/progressdialog.cpp.o

src/progressdialog.i: src/progressdialog.cpp.i
.PHONY : src/progressdialog.i

# target to preprocess a source file
src/progressdialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/progressdialog.cpp.i
.PHONY : src/progressdialog.cpp.i

src/progressdialog.s: src/progressdialog.cpp.s
.PHONY : src/progressdialog.s

# target to generate assembly for a file
src/progressdialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/progressdialog.cpp.s
.PHONY : src/progressdialog.cpp.s

src/qroundprogressbar.o: src/qroundprogressbar.cpp.o
.PHONY : src/qroundprogressbar.o

# target to build an object file
src/qroundprogressbar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/qroundprogressbar.cpp.o
.PHONY : src/qroundprogressbar.cpp.o

src/qroundprogressbar.i: src/qroundprogressbar.cpp.i
.PHONY : src/qroundprogressbar.i

# target to preprocess a source file
src/qroundprogressbar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/qroundprogressbar.cpp.i
.PHONY : src/qroundprogressbar.cpp.i

src/qroundprogressbar.s: src/qroundprogressbar.cpp.s
.PHONY : src/qroundprogressbar.s

# target to generate assembly for a file
src/qroundprogressbar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/qroundprogressbar.cpp.s
.PHONY : src/qroundprogressbar.cpp.s

src/scanlimitstab.o: src/scanlimitstab.cpp.o
.PHONY : src/scanlimitstab.o

# target to build an object file
src/scanlimitstab.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/scanlimitstab.cpp.o
.PHONY : src/scanlimitstab.cpp.o

src/scanlimitstab.i: src/scanlimitstab.cpp.i
.PHONY : src/scanlimitstab.i

# target to preprocess a source file
src/scanlimitstab.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/scanlimitstab.cpp.i
.PHONY : src/scanlimitstab.cpp.i

src/scanlimitstab.s: src/scanlimitstab.cpp.s
.PHONY : src/scanlimitstab.s

# target to generate assembly for a file
src/scanlimitstab.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/scanlimitstab.cpp.s
.PHONY : src/scanlimitstab.cpp.s

src/scanoption.o: src/scanoption.cpp.o
.PHONY : src/scanoption.o

# target to build an object file
src/scanoption.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/scanoption.cpp.o
.PHONY : src/scanoption.cpp.o

src/scanoption.i: src/scanoption.cpp.i
.PHONY : src/scanoption.i

# target to preprocess a source file
src/scanoption.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/scanoption.cpp.i
.PHONY : src/scanoption.cpp.i

src/scanoption.s: src/scanoption.cpp.s
.PHONY : src/scanoption.s

# target to generate assembly for a file
src/scanoption.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/scanoption.cpp.s
.PHONY : src/scanoption.cpp.s

src/scanoptionyn.o: src/scanoptionyn.cpp.o
.PHONY : src/scanoptionyn.o

# target to build an object file
src/scanoptionyn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/scanoptionyn.cpp.o
.PHONY : src/scanoptionyn.cpp.o

src/scanoptionyn.i: src/scanoptionyn.cpp.i
.PHONY : src/scanoptionyn.i

# target to preprocess a source file
src/scanoptionyn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/scanoptionyn.cpp.i
.PHONY : src/scanoptionyn.cpp.i

src/scanoptionyn.s: src/scanoptionyn.cpp.s
.PHONY : src/scanoptionyn.s

# target to generate assembly for a file
src/scanoptionyn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/scanoptionyn.cpp.s
.PHONY : src/scanoptionyn.cpp.s

src/scantab.o: src/scantab.cpp.o
.PHONY : src/scantab.o

# target to build an object file
src/scantab.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/scantab.cpp.o
.PHONY : src/scantab.cpp.o

src/scantab.i: src/scantab.cpp.i
.PHONY : src/scantab.i

# target to preprocess a source file
src/scantab.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/scantab.cpp.i
.PHONY : src/scantab.cpp.i

src/scantab.s: src/scantab.cpp.s
.PHONY : src/scantab.s

# target to generate assembly for a file
src/scantab.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/scantab.cpp.s
.PHONY : src/scantab.cpp.s

src/scheduler.o: src/scheduler.cpp.o
.PHONY : src/scheduler.o

# target to build an object file
src/scheduler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/scheduler.cpp.o
.PHONY : src/scheduler.cpp.o

src/scheduler.i: src/scheduler.cpp.i
.PHONY : src/scheduler.i

# target to preprocess a source file
src/scheduler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/scheduler.cpp.i
.PHONY : src/scheduler.cpp.i

src/scheduler.s: src/scheduler.cpp.s
.PHONY : src/scheduler.s

# target to generate assembly for a file
src/scheduler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/scheduler.cpp.s
.PHONY : src/scheduler.cpp.s

src/schedulescanobject.o: src/schedulescanobject.cpp.o
.PHONY : src/schedulescanobject.o

# target to build an object file
src/schedulescanobject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/schedulescanobject.cpp.o
.PHONY : src/schedulescanobject.cpp.o

src/schedulescanobject.i: src/schedulescanobject.cpp.i
.PHONY : src/schedulescanobject.i

# target to preprocess a source file
src/schedulescanobject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/schedulescanobject.cpp.i
.PHONY : src/schedulescanobject.cpp.i

src/schedulescanobject.s: src/schedulescanobject.cpp.s
.PHONY : src/schedulescanobject.s

# target to generate assembly for a file
src/schedulescanobject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/schedulescanobject.cpp.s
.PHONY : src/schedulescanobject.cpp.s

src/setupfilehandler.o: src/setupfilehandler.cpp.o
.PHONY : src/setupfilehandler.o

# target to build an object file
src/setupfilehandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/setupfilehandler.cpp.o
.PHONY : src/setupfilehandler.cpp.o

src/setupfilehandler.i: src/setupfilehandler.cpp.i
.PHONY : src/setupfilehandler.i

# target to preprocess a source file
src/setupfilehandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/setupfilehandler.cpp.i
.PHONY : src/setupfilehandler.cpp.i

src/setupfilehandler.s: src/setupfilehandler.cpp.s
.PHONY : src/setupfilehandler.s

# target to generate assembly for a file
src/setupfilehandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/setupfilehandler.cpp.s
.PHONY : src/setupfilehandler.cpp.s

src/setuptab.o: src/setuptab.cpp.o
.PHONY : src/setuptab.o

# target to build an object file
src/setuptab.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/setuptab.cpp.o
.PHONY : src/setuptab.cpp.o

src/setuptab.i: src/setuptab.cpp.i
.PHONY : src/setuptab.i

# target to preprocess a source file
src/setuptab.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/setuptab.cpp.i
.PHONY : src/setuptab.cpp.i

src/setuptab.s: src/setuptab.cpp.s
.PHONY : src/setuptab.s

# target to generate assembly for a file
src/setuptab.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/setuptab.cpp.s
.PHONY : src/setuptab.cpp.s

src/translator.o: src/translator.cpp.o
.PHONY : src/translator.o

# target to build an object file
src/translator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/translator.cpp.o
.PHONY : src/translator.cpp.o

src/translator.i: src/translator.cpp.i
.PHONY : src/translator.i

# target to preprocess a source file
src/translator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/translator.cpp.i
.PHONY : src/translator.cpp.i

src/translator.s: src/translator.cpp.s
.PHONY : src/translator.s

# target to generate assembly for a file
src/translator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ClamAV-GUI.dir/build.make CMakeFiles/ClamAV-GUI.dir/src/translator.cpp.s
.PHONY : src/translator.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... ClamAV-GUI_autogen"
	@echo "... ClamAV-GUI_autogen_timestamp_deps"
	@echo "... ClamAV-GUI"
	@echo "... ClamAV-GUI_autogen/EWIEGA46WW/qrc_resources.o"
	@echo "... ClamAV-GUI_autogen/EWIEGA46WW/qrc_resources.i"
	@echo "... ClamAV-GUI_autogen/EWIEGA46WW/qrc_resources.s"
	@echo "... ClamAV-GUI_autogen/mocs_compilation.o"
	@echo "... ClamAV-GUI_autogen/mocs_compilation.i"
	@echo "... ClamAV-GUI_autogen/mocs_compilation.s"
	@echo "... src/cfilesystemmodel.o"
	@echo "... src/cfilesystemmodel.i"
	@echo "... src/cfilesystemmodel.s"
	@echo "... src/clamav_ctrl.o"
	@echo "... src/clamav_ctrl.i"
	@echo "... src/clamav_ctrl.s"
	@echo "... src/clamav_gui.o"
	@echo "... src/clamav_gui.i"
	@echo "... src/clamav_gui.s"
	@echo "... src/clamdconfcomboboxoption.o"
	@echo "... src/clamdconfcomboboxoption.i"
	@echo "... src/clamdconfcomboboxoption.s"
	@echo "... src/clamdconfspinboxoption.o"
	@echo "... src/clamdconfspinboxoption.i"
	@echo "... src/clamdconfspinboxoption.s"
	@echo "... src/clamdconfstringoption.o"
	@echo "... src/clamdconfstringoption.i"
	@echo "... src/clamdconfstringoption.s"
	@echo "... src/clamdmanager.o"
	@echo "... src/clamdmanager.i"
	@echo "... src/clamdmanager.s"
	@echo "... src/dragablepushbutton.o"
	@echo "... src/dragablepushbutton.i"
	@echo "... src/dragablepushbutton.s"
	@echo "... src/freshclamsetter.o"
	@echo "... src/freshclamsetter.i"
	@echo "... src/freshclamsetter.s"
	@echo "... src/highlighter.o"
	@echo "... src/highlighter.i"
	@echo "... src/highlighter.s"
	@echo "... src/includeexcludeoptions.o"
	@echo "... src/includeexcludeoptions.i"
	@echo "... src/includeexcludeoptions.s"
	@echo "... src/infodialog.o"
	@echo "... src/infodialog.i"
	@echo "... src/infodialog.s"
	@echo "... src/logviewerobject.o"
	@echo "... src/logviewerobject.i"
	@echo "... src/logviewerobject.s"
	@echo "... src/logviewobject.o"
	@echo "... src/logviewobject.i"
	@echo "... src/logviewobject.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/myframe.o"
	@echo "... src/myframe.i"
	@echo "... src/myframe.s"
	@echo "... src/optionsdialog.o"
	@echo "... src/optionsdialog.i"
	@echo "... src/optionsdialog.s"
	@echo "... src/partiallogobject.o"
	@echo "... src/partiallogobject.i"
	@echo "... src/partiallogobject.s"
	@echo "... src/profilemanager.o"
	@echo "... src/profilemanager.i"
	@echo "... src/profilemanager.s"
	@echo "... src/profilewizarddialog.o"
	@echo "... src/profilewizarddialog.i"
	@echo "... src/profilewizarddialog.s"
	@echo "... src/progressdialog.o"
	@echo "... src/progressdialog.i"
	@echo "... src/progressdialog.s"
	@echo "... src/qroundprogressbar.o"
	@echo "... src/qroundprogressbar.i"
	@echo "... src/qroundprogressbar.s"
	@echo "... src/scanlimitstab.o"
	@echo "... src/scanlimitstab.i"
	@echo "... src/scanlimitstab.s"
	@echo "... src/scanoption.o"
	@echo "... src/scanoption.i"
	@echo "... src/scanoption.s"
	@echo "... src/scanoptionyn.o"
	@echo "... src/scanoptionyn.i"
	@echo "... src/scanoptionyn.s"
	@echo "... src/scantab.o"
	@echo "... src/scantab.i"
	@echo "... src/scantab.s"
	@echo "... src/scheduler.o"
	@echo "... src/scheduler.i"
	@echo "... src/scheduler.s"
	@echo "... src/schedulescanobject.o"
	@echo "... src/schedulescanobject.i"
	@echo "... src/schedulescanobject.s"
	@echo "... src/setupfilehandler.o"
	@echo "... src/setupfilehandler.i"
	@echo "... src/setupfilehandler.s"
	@echo "... src/setuptab.o"
	@echo "... src/setuptab.i"
	@echo "... src/setuptab.s"
	@echo "... src/translator.o"
	@echo "... src/translator.i"
	@echo "... src/translator.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

