#include "infodialog.h"
#include "ui_infodialog.h"

infoDialog::infoDialog(QWidget *parent) : QWidget(parent), ui(new Ui::infoDialog)
{
 QString m_version = "1.1.5 (QT5)";

    QString m_infoText =  "<html>";
            m_infoText += "  <head/>";
            m_infoText += "    <body>";
            m_infoText += "      <p align='center'>";
            m_infoText += "        <span style=' font-size:22px; color:#000080;'>ClamAV-GUI</span>";
            m_infoText += "      </p>";
            m_infoText += "      <p align='center'>";
            m_infoText += "        <span style=' font-size:15px; color:#000000;'><br/>Version " + m_version + " (2015 - 2025), published unter GPL 3.0</span>";
            m_infoText += "      </p>";
            m_infoText += "      <hr/>";
            m_infoText += "      <table border='0' style=' margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px;' align='center' cellspacing='2' cellpadding='0'>";
            m_infoText += "        <tr>";
            m_infoText += "          <td colspan='7'>";
            m_infoText += "            <p>";
            m_infoText += "              <span style=' font-size:14px; font-weight:700; text-decoration: underline;'>Author:</span>";
            m_infoText += "              <span style=' font-size:14px;'>  Joerg Macedo da Costa Zopes &lt;joerg.zopes@gmx.de&gt;<br/></span>";
            m_infoText += "            </p>";
            m_infoText += "          </td>";
            m_infoText += "        </tr>";
            m_infoText += "        <tr>";
            m_infoText += "          <td>";
            m_infoText += "            <p>";
            m_infoText += "              <span style=' font-size:14px; font-weight:700; text-decoration: underline;'>Translators</span>";
            m_infoText += "            </p>";
            m_infoText += "          </td>";
            m_infoText += "        </tr>";
            m_infoText += "        <tr>";
            m_infoText += "          <td>";
            m_infoText += "            <p>";
            m_infoText += "              <img src='qrc:///icons/icons/dansk.png'/>";
            m_infoText += "              <span style=' font-size:14px;'> Danish:</span>";
            m_infoText += "            </p>";
            m_infoText += "          </td>";
            m_infoText += "          <td>";
            m_infoText += "            <p>";
            m_infoText += "              <span style=' font-size:14px;'/>";
            m_infoText += "            </p>";
            m_infoText += "          </td>";
            m_infoText += "          <td>";
            m_infoText += "            <p>";
            m_infoText += "              <span style=' font-size:14px;'>Martin Eilssøe &lt;martin.eilsoe@gmail.com&gt;</span>";
            m_infoText += "            </p>";
            m_infoText += "          </td>";
            m_infoText += "          <td>";
            m_infoText += "            <p>";
            m_infoText += "              <span style=' font-size:14px;'/>";
            m_infoText += "            </p>";
            m_infoText += "          </td>";
            m_infoText += "          <td>";
            m_infoText += "            <p>";
            m_infoText += "              <img src='qrc:///icons/icons/spain.png'/>";
            m_infoText += "              <span style=' font-size:14px;'> Spanish:</span>";
            m_infoText += "            </p>";
            m_infoText += "          </td>";
            m_infoText += "          <td>";
            m_infoText += "            <p>";
            m_infoText += "              <span style=' font-size:14px;'/>";
            m_infoText += "            </p>";
            m_infoText += "          </td>";
            m_infoText += "          <td>";
            m_infoText += "            <p>";
            m_infoText += "              <span style=' font-size:14px;'>Pedro Álamo &lt;palamodz@gmail.com&gt;</span>";
            m_infoText += "            </p>";
            m_infoText += "          </td>";
            m_infoText += "        </tr>";
            m_infoText += "        <tr>";
            m_infoText += "          <td>";
            m_infoText += "            <p>";
            m_infoText += "              <img src='qrc:///icons/icons/germany.png'/>";
            m_infoText += "              <span style=' font-size:14px;'> German:</span>";
            m_infoText += "            </p>";
            m_infoText += "          </td>";
            m_infoText += "          <td>";
            m_infoText += "            <p>";
            m_infoText += "              <span style=' font-size:14px;'/>";
            m_infoText += "            </p>";
            m_infoText += "          </td>";
            m_infoText += "          <td>";
            m_infoText += "            <p>";
            m_infoText += "              <span style=' font-size:14px;'>translated by the author.</span>";
            m_infoText += "            </p>";
            m_infoText += "          </td>";
            m_infoText += "          <td>";
            m_infoText += "            <p>";
            m_infoText += "              <span style=' font-size:14px;'/>";
            m_infoText += "            </p>";
            m_infoText += "          </td>";
            m_infoText += "          <td>";
            m_infoText += "            <p>";
            m_infoText += "              <img src='qrc:///icons/icons/france.png'/>";
            m_infoText += "              <span style=' font-size:14px;'> French:</span>";
            m_infoText += "            </p>";
            m_infoText += "          </td>";
            m_infoText += "          <td>";
            m_infoText += "            <p>";
            m_infoText += "              <span style=' font-size:14px;'/>";
            m_infoText += "            </p>";
            m_infoText += "          </td>";
            m_infoText += "          <td>";
            m_infoText += "            <p>";
            m_infoText += "              <span style=' font-size:14px;'>Not be named </span>";
            m_infoText += "            </p>";
            m_infoText += "          </td>";
            m_infoText += "        </tr>";
            m_infoText += "        <tr>";
            m_infoText += "          <td>";
            m_infoText += "            <p>";
            m_infoText += "              <img src='qrc:///icons/icons/Portugal.png'/>";
            m_infoText += "              <span style=' font-size:14px;'> Portuguese:</span>";
            m_infoText += "            </p>";
            m_infoText += "          </td>";
            m_infoText += "          <td>";
            m_infoText += "            <p>";
            m_infoText += "              <span style=' font-size:14px;'/>";
            m_infoText += "            </p>";
            m_infoText += "          </td>";
            m_infoText += "          <td>";
            m_infoText += "            <p>";
            m_infoText += "              <span style=' font-size:14px;'>Translated by the author.</span>";
            m_infoText += "            </p>";
            m_infoText += "          </td>";
            m_infoText += "          <td>";
            m_infoText += "            <p>";
            m_infoText += "              <span style=' font-size:14px;'/>";
            m_infoText += "            </p>";
            m_infoText += "          </td>";
            m_infoText += "          <td>";
            m_infoText += "            <p>";
            m_infoText += "              <img src='qrc:///icons/icons/Brasil.png'/>";
            m_infoText += "              <span style=' font-size:14px;'> Brasilian:</span>";
            m_infoText += "            </p>";
            m_infoText += "          </td>";
            m_infoText += "          <td>";
            m_infoText += "            <p>";
            m_infoText += "              <span style=' font-size:14px;'/>";
            m_infoText += "            </p>";
            m_infoText += "          </td>";
            m_infoText += "          <td>";
            m_infoText += "            <p>";
            m_infoText += "              <span style=' font-size:14px;'>Translated by the author.</span>";
            m_infoText += "            </p>";
            m_infoText += "          </td>";
            m_infoText += "        </tr>";
            m_infoText += "        <tr>";
            m_infoText += "          <td>";
            m_infoText += "            <p>";
            m_infoText += "              <img src='qrc:///icons/icons/GB.png'/>";
            m_infoText += "              <span style=' font-size:14px;'> English:</span>";
            m_infoText += "            </p>";
            m_infoText += "          </td>";
            m_infoText += "          <td>";
            m_infoText += "            <p>";
            m_infoText += "              <span style=' font-size:14px;'/>";
            m_infoText += "            </p>";
            m_infoText += "          </td>";
            m_infoText += "          <td>";
            m_infoText += "            <p>";
            m_infoText += "              <span style=' font-size:14px;'>Translated by the author.</span>";
            m_infoText += "            </p>";
            m_infoText += "          </td>";
            m_infoText += "          <td>";
            m_infoText += "            <p>";
            m_infoText += "              <span style=' font-size:14px;'/>";
            m_infoText += "            </p>";
            m_infoText += "          </td>";
            m_infoText += "          <td>";
            m_infoText += "            <p>";
            m_infoText += "              <img src='qrc:///icons/icons/italy.png'/>";
            m_infoText += "              <span style=' font-size:14px;'> Italian:</span>";
            m_infoText += "            </p>";
            m_infoText += "          </td>";
            m_infoText += "          <td>";
            m_infoText += "            <p>";
            m_infoText += "              <span style=' font-size:14px;'/>";
            m_infoText += "            </p>";
            m_infoText += "          </td>";
            m_infoText += "          <td>";
            m_infoText += "            <p>";
            m_infoText += "              <span style=' font-size:14px;'>translated by DeepL</span>";
            m_infoText += "            </p>";
            m_infoText += "          </td>";
            m_infoText += "        </tr>";
            m_infoText += "      </table>";
            m_infoText += "      <hr/>";
            m_infoText += "      <table border='0' style=' margin-top:20px; margin-bottom:0px; margin-left:20px; margin-right:0px;' cellspacing='2' cellpadding='0'>";
            m_infoText += "        <tr>";
            m_infoText += "          <td>";
            m_infoText += "            <p>";
            m_infoText += "              <img src='qrc:///icons/icons/ukraine.png'/>";
            m_infoText += "            </p>";
            m_infoText += "          </td>";
            m_infoText += "          <td>";
            m_infoText += "            <p>";
            m_infoText += "              <span style=' font-size:14px;'/>";
            m_infoText += "            </p>";
            m_infoText += "          </td>";
            m_infoText += "          <td>";
            m_infoText += "            <p>";
            m_infoText += "              <span style=' font-size:14px;'>A special thanks goes to UALinux &lt;main@ualinux.com&gt;.<br/>";
            m_infoText += "              We were in close contact for more than a week and<br/>";
            m_infoText += "              with their help I was able to fix some bugs<br/>";
            m_infoText += "              and implement useful new features.<br/>";
            m_infoText += "              <br/>";
            m_infoText += "              Many thanks for that.</span>";
            m_infoText += "            </p>";
            m_infoText += "          </td>";
            m_infoText += "          <td>";
            m_infoText += "            <p>";
            m_infoText += "              <span style=' font-size:14px;'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>";
            m_infoText += "            </p>";
            m_infoText += "          </td>";
            m_infoText += "          <td>";
            m_infoText += "            <p>";
            m_infoText += "              <span style=' font-size:14px;'>Another big Thank you! goes to Neil Grayson.<br/>";
            m_infoText += "              He used to work in electronics design and software development<br/>";
            m_infoText += "              and drew my attention to something I had completely missed.<br/>";
            m_infoText += "              <br/>";
            m_infoText += "              Many thanks for that. <font style='font-size:24px;color:#d4de62'>&#128521;</font></span>";
            m_infoText += "            </p>";
            m_infoText += "          </td>";
            m_infoText += "        </tr>";
            m_infoText += "      </table>";
            m_infoText += "    </body>";
            m_infoText += "  </html>";
    ui->setupUi(this);
    ui->creditTextEdit->setHtml(m_infoText);
}

infoDialog::~infoDialog()
{
    delete ui;
}
